apiVersion: v1
kind: ServiceAccount
metadata:
  name: operation-phase
  namespace: green-devops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operation-phase-scaler
  namespace: green-devops
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operation-phase-scaling
  namespace: green-devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operation-phase-scaler
subjects:
- kind: ServiceAccount
  name: operation-phase
  namespace: green-devops
