apiVersion: v1
kind: Service
metadata:
  name: operation-phase
  namespace: green-devops
  labels:
    app: operation-phase
spec:
  type: ClusterIP
  selector:
    app: operation-phase
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
